repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.8
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ src, tests, --fix ]
    # Run the formatter.
    - id: ruff-format
      args: [ src, tests ]

# Uncomment to enable pyright hook

# - repo: local
#   hooks:
#     - id: pyright
#       name: pyright check
#       entry: uv run pyright src/
#       language: system
#       pass_filenames: false